import{a as L,i as a,S as q}from"./assets/vendor-WLD9_8QG.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))y(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&y(c)}).observe(document,{childList:!0,subtree:!0});function l(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function y(e){if(e.ep)return;e.ep=!0;const o=l(e);fetch(e.href,o)}})();const v="48568808-b5581b6c1359d9abd76100469",E="https://pixabay.com/api/";async function f(t,r=1){try{return(await L.get(E,{params:{key:v,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}catch{return a.error({title:"Error",message:"Failed to fetch images"}),{hits:[],totalHits:0}}}const h=document.querySelector(".gallery"),w=new q(".gallery a",{captionsData:"alt",captionDelay:250});function P(){h.innerHTML=""}function m(t){if(t.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please, try again"});return}const r=t.map(({webformatURL:l,largeImageURL:y,tags:e,likes:o,views:c,comments:b,downloads:S})=>`
      <a href="${y}" class="gallery-item">
        <img src="${l}" alt="${e}" loading="lazy" />
        <div class="info">
          <p><br>Likes:</br> ${o}</p>
          <p><br>Views:</br> ${c}</p>
          <p><br>Comments:</br> ${b}</p>
          <p><br>Downloads:</br> ${S}</p>
        </div>
      </a>
    `).join("");h.insertAdjacentHTML("beforeend",r),w.refresh()}const g=document.querySelector("#search-form"),i=document.querySelector(".loader");document.querySelector(".gallery");const s=document.querySelector(".more");let d="",n=1,p=0;const u=15;g.addEventListener("submit",async t=>{if(t.preventDefault(),d=g.querySelector("input").value.trim(),!d){a.warning({title:"Warning",message:"Please enter a search term"});return}n=1,P(),s.style.display="none",i.style.display="block";try{const r=await f(d,n,u);if(i.style.display="none",r.hits.length===0){m([]);return}p=r.totalHits,m(r.hits),n*u<p&&(s.style.display="block")}catch(r){console.error("Error fetching images:",r),a.error({title:"Error",message:"Failed to load images. Try again later."}),i.style.display="none"}});s.addEventListener("click",async()=>{n++,s.style.display="none",i.style.display="block";try{const t=await f(d,n,u);if(i.style.display="none",t.hits.length===0){a.info({message:"No more images available."});return}m(t.hits),n*u>=p?(s.style.display="none",a.info({message:"We're sorry, but you've reached the end of search results."})):s.style.display="block",$()}catch(t){console.error("Error fetching more images:",t),a.error({title:"Error",message:"Failed to load more images. Try again later."}),i.style.display="none",s.style.display="block"}});function $(){var r;const t=((r=document.querySelector(".gallery-item"))==null?void 0:r.getBoundingClientRect().height)||200;window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
